const { readFile } = require('fs/promises');

const config = {
  data: {
    permalink: '/admin/config.yml',
  },
  render: async function ({ config, locale }) {
    const texts = locale[config.language] || locale.en;
    const file = await readFile('./src/decap/config.yml');
    const configFile = file
      .toString()
      .replace(/'{{site_url}}'/gi, config.url)
      .replace(/'{{language}}'/gi, config.language)
      .replace(/'{{posts.plural}}'/gi, texts.posts.plural)
      .replace(/'{{posts.singular}}'/gi, texts.posts.singular)
      .replace(/'{{posts.title.label}}'/gi, texts.posts.title.label)
      .replace(/'{{posts.title.hint}}'/gi, texts.posts.title.hint)
      .replace(/'{{posts.seo.label}}'/gi, texts.posts.seo.label)
      .replace(/'{{posts.seo.title.label}}'/gi, texts.posts.seo.title.label)
      .replace(/'{{posts.seo.title.hint}}'/gi, texts.posts.seo.title.hint)
      .replace(/'{{posts.seo.slug.label}}'/gi, texts.posts.seo.slug.label)
      .replace(/'{{posts.seo.slug.hint}}'/gi, texts.posts.seo.slug.hint)
      .replace(/'{{posts.seo.description.label}}'/gi, texts.posts.seo.description.label)
      .replace(/'{{posts.seo.description.error}}'/gi, texts.posts.seo.description.error)
      .replace(/'{{posts.seo.description.hint}}'/gi, texts.posts.seo.description.hint)
      .replace(/'{{posts.info.label}}'/gi, texts.posts.info.label)
      .replace(/'{{posts.info.title.label}}'/gi, texts.posts.info.title.label)
      .replace(/'{{posts.info.title.hint}}'/gi, texts.posts.info.title.hint)
      .replace(/'{{posts.info.category.label}}'/gi, texts.posts.info.category.label)
      .replace(/'{{posts.info.category.hint}}'/gi, texts.posts.info.category.hint)
      .replace(/'{{posts.info.date.label}}'/gi, texts.posts.info.date.label)
      .replace(/'{{posts.info.date.hint}}'/gi, texts.posts.info.date.hint)
      .replace(/'{{posts.info.author.label}}'/gi, texts.posts.info.author.label)
      .replace(/'{{posts.info.author.hint}}'/gi, texts.posts.info.author.hint)
      .replace(/'{{posts.info.excerpt.label}}'/gi, texts.posts.info.excerpt.label)
      .replace(/'{{posts.info.excerpt.hint}}'/gi, texts.posts.info.excerpt.hint)
      .replace(/'{{posts.heroImage.label}}'/gi, texts.posts.heroImage.label)
      .replace(/'{{posts.heroImage.hint}}'/gi, texts.posts.heroImage.hint)
      .replace(/'{{posts.body.label}}'/gi, texts.posts.body.label)
      .replace(/'{{posts.body.hint}}'/gi, texts.posts.body.hint)
      .replace(/'{{categories.plural}}'/gi, texts.categories.plural)
      .replace(/'{{categories.singular}}'/gi, texts.categories.singular)
      .replace(/'{{categories.title.label}}'/gi, texts.categories.title.label)
      .replace(/'{{categories.title.hint}}'/gi, texts.categories.title.hint)
      .replace(/'{{categories.seo.label}}'/gi, texts.categories.seo.label)
      .replace(/'{{categories.seo.title.label}}'/gi, texts.categories.seo.title.label)
      .replace(/'{{categories.seo.title.hint}}'/gi, texts.categories.seo.title.hint)
      .replace(/'{{categories.seo.slug.label}}'/gi, texts.categories.seo.slug.label)
      .replace(/'{{categories.seo.slug.hint}}'/gi, texts.categories.seo.slug.hint)
      .replace(/'{{categories.seo.description.label}}'/gi, texts.categories.seo.description.label)
      .replace(/'{{categories.seo.description.error}}'/gi, texts.categories.seo.description.error)
      .replace(/'{{categories.seo.description.hint}}'/gi, texts.categories.seo.description.hint)
      .replace(/'{{categories.seo.heading.label}}'/gi, texts.categories.seo.heading.label)
      .replace(/'{{categories.seo.heading.hint}}'/gi, texts.categories.seo.heading.hint)
      .replace(/'{{categories.body.label}}'/gi, texts.categories.body.label)
      .replace(/'{{categories.body.hint}}'/gi, texts.categories.body.hint)
      .replace(/'{{authors.plural}}'/gi, texts.authors.plural)
      .replace(/'{{authors.singular}}'/gi, texts.authors.singular)
      .replace(/'{{authors.title.label}}'/gi, texts.authors.title.label)
      .replace(/'{{authors.title.hint}}'/gi, texts.authors.title.hint)
      .replace(/'{{authors.photo.label}}'/gi, texts.authors.photo.label)
      .replace(/'{{authors.photo.hint}}'/gi, texts.authors.photo.hint)
      .replace(/'{{authors.email.label}}'/gi, texts.authors.email.label)
      .replace(/'{{authors.email.error}}'/gi, texts.authors.email.error)
      .replace(/'{{authors.email.hint}}'/gi, texts.authors.email.hint)
      .replace(/'{{pages.plural}}'/gi, texts.pages.plural)
      .replace(/'{{pages.singular}}'/gi, texts.pages.singular)
      .replace(/'{{pages.title.label}}'/gi, texts.pages.title.label)
      .replace(/'{{pages.title.hint}}'/gi, texts.pages.title.hint)
      .replace(/'{{pages.seo.label}}'/gi, texts.pages.seo.label)
      .replace(/'{{pages.seo.title.label}}'/gi, texts.pages.seo.title.label)
      .replace(/'{{pages.seo.title.hint}}'/gi, texts.pages.seo.title.hint)
      .replace(/'{{pages.seo.slug.label}}'/gi, texts.pages.seo.slug.label)
      .replace(/'{{pages.seo.slug.hint}}'/gi, texts.pages.seo.slug.hint)
      .replace(/'{{pages.seo.description.label}}'/gi, texts.pages.seo.description.label)
      .replace(/'{{pages.seo.description.error}}'/gi, texts.pages.seo.description.error)
      .replace(/'{{pages.seo.description.hint}}'/gi, texts.pages.seo.description.hint)
      .replace(/'{{pages.seo.heading.label}}'/gi, texts.pages.seo.heading.label)
      .replace(/'{{pages.seo.heading.hint}}'/gi, texts.pages.seo.heading.hint)
      .replace(/'{{pages.body.label}}'/gi, texts.pages.body.label)
      .replace(/'{{pages.body.hint}}'/gi, texts.pages.body.hint)
      .replace(/'{{settings.label}}'/gi, texts.settings.label)
      .replace(/'{{settings.home.label}}'/gi, texts.settings.home.label)
      .replace(/'{{settings.home.seo.label}}'/gi, texts.settings.home.seo.label)
      .replace(/'{{settings.home.seo.title.label}}'/gi, texts.settings.home.seo.title.label)
      .replace(/'{{settings.home.seo.title.hint}}'/gi, texts.settings.home.seo.title.hint)
      .replace(/'{{settings.home.seo.description.label}}'/gi, texts.settings.home.seo.description.label)
      .replace(/'{{settings.home.seo.description.hint}}'/gi, texts.settings.home.seo.description.hint)
      .replace(/'{{settings.home.seo.heading.label}}'/gi, texts.settings.home.seo.heading.label)
      .replace(/'{{settings.home.seo.heading.hint}}'/gi, texts.settings.home.seo.heading.hint)
      .replace(/'{{settings.home.body.label}}'/gi, texts.settings.home.body.label)
      .replace(/'{{settings.home.body.hint}}'/gi, texts.settings.home.body.hint)
      .replace(/'{{settings.navigation.label}}'/gi, texts.settings.navigation.label)
      .replace(/'{{settings.navigation.categories.label}}'/gi, texts.settings.navigation.categories.label)
      .replace(/'{{settings.navigation.categories.hint}}'/gi, texts.settings.navigation.categories.hint)
      .replace(/'{{settings.navigation.categories.category}}'/gi, texts.settings.navigation.categories.category)
      .replace(/'{{settings.navigation.pages.label}}'/gi, texts.settings.navigation.pages.label)
      .replace(/'{{settings.navigation.pages.hint}}'/gi, texts.settings.navigation.pages.hint)
      .replace(/'{{settings.navigation.pages.page}}'/gi, texts.settings.navigation.pages.page)
      .replace(/'{{settings.logo.label}}'/gi, texts.settings.logo.label)
      .replace(/'{{settings.logo.multicolor.label}}'/gi, texts.settings.logo.multicolor.label)
      .replace(/'{{settings.logo.multicolor.hint}}'/gi, texts.settings.logo.multicolor.hint)
      .replace(/'{{settings.logo.onecolor.label}}'/gi, texts.settings.logo.onecolor.label)
      .replace(/'{{settings.logo.onecolor.hint}}'/gi, texts.settings.logo.onecolor.hint)
      .replace(/'{{settings.socialMedia.label}}'/gi, texts.settings.socialMedia.label)
      .replace(/'{{settings.socialMedia.links.label}}'/gi, texts.settings.socialMedia.links.label)
      .replace(/'{{settings.socialMedia.links.hint}}'/gi, texts.settings.socialMedia.links.hint)
      .replace(/'{{settings.socialMedia.links.name.label}}'/gi, texts.settings.socialMedia.links.name.label)
      .replace(/'{{settings.socialMedia.links.name.hint}}'/gi, texts.settings.socialMedia.links.name.hint)
      .replace(/'{{settings.socialMedia.links.url.label}}'/gi, texts.settings.socialMedia.links.url.label)
      .replace(/'{{settings.socialMedia.links.url.hint}}'/gi, texts.settings.socialMedia.links.url.hint)
      .replace(/'{{settings.footer.label}}'/gi, texts.settings.footer.label)
      .replace(/'{{settings.footer.pages.label}}'/gi, texts.settings.footer.pages.label)
      .replace(/'{{settings.footer.pages.hint}}'/gi, texts.settings.footer.pages.hint)
      .replace(/'{{settings.footer.pages.page}}'/gi, texts.settings.footer.pages.page);
    return configFile;
  },
};

module.exports = config;
