backend:
  name: github
  repo: jucegt/speedy-pages
  branch: develop
  commit_messages:
    create: 'cms: created {{collection}} “{{slug}}”'
    update: 'cms: updated {{collection}} “{{slug}}”'
    delete: 'cms: deleted {{collection}} “{{slug}}”'
    uploadMedia: 'cms: uploaded “{{path}}”'
    deleteMedia: 'cms: deleted “{{path}}”'

publish_mode: editorial_workflow
media_folder: content/static
public_folder: /

site_url: '{{site_url}}'
display_url: '{{site_url}}'

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/posts'
    create: true
    path: '{{year}}/{{month}}/{{slug}}'
    slug: '{{fields.slug}}'
    media_folder: ../../../static
    public_folder: /
    fields:
      - label: 'SEO'
        name: 'seo'
        widget: 'object'
        summary: '{{fields.title}}'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Title displayed in Google search results.' }
          - { label: 'Slug', name: 'slug', widget: 'string', hint: 'Link structure displayed in the navigation bar.' }
          - {
              label: 'Description',
              name: 'description',
              widget: 'text',
              pattern: ['^.{140,160}$', 'The description should be between 140 and 160 characters'],
              hint: 'Description displayed in Google search results.',
            }
      - label: 'Information'
        name: 'info'
        widget: 'object'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'string', hint: 'Title displayed in the post page.' }
          - {
              label: 'Category',
              name: 'category',
              widget: 'relation',
              collection: 'categories',
              search_fields: ['title'],
              value_field: 'title',
              hint: 'Category displayed in the post page.',
            }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', hint: 'Date displayed in the post page.' }
          - {
              label: 'Author',
              name: 'author',
              widget: 'relation',
              collection: 'authors',
              search_fields: ['title'],
              value_field: 'title',
              hint: 'Author displayed in the post page.',
            }
          - { label: 'Excerpt', name: 'excerpt', widget: 'text', hint: 'Excerpt displayed in the post page.' }
      - label: 'Content'
        name: 'content'
        widget: 'object'
        fields:
          - { label: 'Hero Image', name: 'image', widget: image, hint: 'Hero image displayed in the post page.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Content displayed in the post page.' }

  - name: 'categories'
    label: 'Categories'
    label_singular: 'Category'
    folder: 'content/categories'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Show in Menu', name: 'showmenu', widget: 'boolean', required: false }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          pattern: ['^.{140,160}$', 'The description should be between 140 and 160 characters'],
        }
      - { label: 'Heading', name: 'heading', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: 'content/authors'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Photo', name: 'photo', widget: image }

  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content/pages'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false
    files:
      - label: 'SEO Information'
        name: 'seoinfo'
        file: 'content/settings/seo.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Description',
              name: 'description',
              widget: 'text',
              pattern: ['^.{140,160}$', 'The description should be between 140 and 160 characters'],
            }
          - { label: 'Heading on Home', name: heading, widget: 'string' }
          - { label: 'Info on Home', name: 'info', widget: 'markdown' }

      - label: Logo
        name: logo
        file: 'content/settings/logo.md'
        fields:
          - { label: 'Multi-Color', name: 'multicolor', widget: 'code' }
          - { label: 'One Color', name: 'onecolor', widget: 'code' }

      - label: 'Social Media'
        name: 'socialmedia'
        file: 'content/settings/social-media.md'
        fields:
          - label: 'Social Links'
            name: 'sociallinks'
            widget: 'list'
            summary: '{{fields.name}} - {{fields.url}}'
            fields:
              - {
                  label: 'Name',
                  name: 'name',
                  widget: 'select',
                  options:
                    [
                      'Behance',
                      'Discrod',
                      'Dribble',
                      'Facebook',
                      'GitHub',
                      'GitLab',
                      'Google',
                      'Instagram',
                      'LinkedIn',
                      'Medium',
                      'Pinterest',
                      'Pocket',
                      'RSS',
                      'Snapchat',
                      'StackOverflow',
                      'Telegram',
                      'TikTok',
                      'Twitter',
                      'YouTube',
                      'Yelp',
                    ],
                }
              - { label: 'URL', name: 'url', widget: 'string' }

      - label: 'Links'
        name: 'links'
        file: 'content/settings/links.md'
        fields:
          - label: 'Footer Pages'
            name: 'footerpages'
            widget: 'list'
            summary: '{{fields.page}}'
            fields:
              - {
                  label: 'Page',
                  name: 'page',
                  widget: 'relation',
                  collection: 'pages',
                  search_fields: ['title'],
                  value_field: 'title',
                }
