backend:
  name: github
  repo: jucegt/speedy-pages
  branch: develop
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: content/static
public_folder: /

site_url: '{{site_url}}'
display_url: '{{site_url}}'

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/posts'
    create: true
    path: '{{year}}/{{month}}/{{slug}}'
    slug: '{{fields.slug}}'
    media_folder: ../../../static
    public_folder: /
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          search_fields: ['title'],
          value_field: 'title',
        }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          pattern: ['.{140,160}', 'The description should be between 140 and 160 characters.'],
        }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'categories',
          search_fields: ['title'],
          value_field: 'title',
        }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'categories'
    label: 'Categories'
    label_singular: 'Category'
    folder: 'content/categories'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Show in Menu', name: 'showmenu', widget: 'boolean', required: false }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          pattern: ['.{140,160}', 'The description should be between 140 and 160 characters.'],
        }
      - { label: 'Heading', name: 'heading', widget: 'string' }
      - { label: 'Info', name: 'info', widget: 'text' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: 'content/authors'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content/pages'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false
    files:
      - label: 'SEO Information'
        name: 'seoinfo'
        file: 'content/settings/seo.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Description',
              name: 'description',
              widget: 'text',
              pattern: ['.{140,160}', 'The description should be between 140 and 160 characters.'],
            }
          - { label: 'Heading on Home', name: heading, widget: 'string' }
          - { label: 'Info on Home', name: 'info', widget: 'text' }

      - label: Logo
        name: logo
        file: 'content/settings/logo.md'
        fields:
          - { label: 'Multi-Color', name: 'multicolor', widget: 'code' }
          - { label: 'One Color', name: 'onecolor', widget: 'code' }

      - label: 'Social Media'
        name: 'socialmedia'
        file: 'content/settings/social-media.md'
        fields:
          - label: 'Social Links'
            name: 'sociallinks'
            widget: 'list'
            summary: '{{fields.name}} - {{fields.url}}'
            fields:
              - {
                  label: 'Name',
                  name: 'name',
                  widget: 'select',
                  options:
                    [
                      'Behance',
                      'Discrod',
                      'Dribble',
                      'Facebook',
                      'GitHub',
                      'GitLab',
                      'Google',
                      'Instagram',
                      'LinkedIn',
                      'Medium',
                      'Pinterest',
                      'Pocket',
                      'RSS',
                      'Snapchat',
                      'StackOverflow',
                      'Telegram',
                      'TikTok',
                      'Twitter',
                      'YouTube',
                      'Yelp',
                    ],
                }
              - { label: 'URL', name: 'url', widget: 'string' }

      - label: 'Links'
        name: 'links'
        file: 'content/settings/links.md'
        fields:
          - label: 'Footer Pages'
            name: 'footerpages'
            widget: 'list'
            summary: '{{fields.page}}'
            fields:
              - {
                  label: 'Page',
                  name: 'page',
                  widget: 'relation',
                  collection: 'pages',
                  search_fields: ['title'],
                  value_field: 'title',
                }
