backend:
  name: github
  repo: jucegt/speedy-pages
  branch: develop
  commit_messages:
    create: 'cms: created {{collection}} “{{slug}}”'
    update: 'cms: updated {{collection}} “{{slug}}”'
    delete: 'cms: deleted {{collection}} “{{slug}}”'
    uploadMedia: 'cms: uploaded “{{path}}”'
    deleteMedia: 'cms: deleted “{{path}}”'

publish_mode: editorial_workflow
media_folder: content/static
public_folder: /

locale: '{{language}}'
site_url: '{{site_url}}'
display_url: '{{site_url}}'

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'posts'
    label: '{{posts.plural}}'
    label_singular: '{{posts.singular}}'
    folder: 'content/posts'
    create: true
    path: '{{year}}/{{month}}/{{slug}}'
    slug: '{{fields.seo.slug}}'
    media_folder: ../../../static
    public_folder: /
    fields:
      - { label: '{{posts.title.label}}', name: 'title', widget: 'string', hint: '{{posts.title.hint}}' }
      - label: '{{posts.seo.label}}'
        name: 'seo'
        widget: 'object'
        summary: '{{fields.title}}'
        fields:
          - { label: '{{posts.seo.title.label}}', name: 'title', widget: 'string', hint: '{{posts.seo.title.hint}}' }
          - { label: '{{posts.seo.slug.label}}', name: 'slug', widget: 'string', hint: '{{posts.seo.slug.hint}}' }
          - {
              label: '{{posts.seo.description.label}}',
              name: 'description',
              widget: 'text',
              pattern: ['^.{140,160}$', '{{posts.seo.description.error}}'],
              hint: '{{posts.seo.description.hint}}',
            }
      - label: '{{posts.info.label}}'
        name: 'info'
        widget: 'object'
        summary: '{{fields.title}}'
        fields:
          - { label: '{{posts.info.title.label}}', name: 'title', widget: 'string', hint: '{{posts.info.title.hint}}' }
          - {
              label: '{{posts.info.category.label}}',
              name: 'category',
              widget: 'relation',
              collection: 'categories',
              search_fields: ['seo.title'],
              value_field: 'seo.slug',
              display_fields: ['seo.title'],
              hint: '{{posts.info.category.hint}}',
            }
          - { label: '{{posts.info.date.label}}', name: 'date', widget: 'datetime', hint: '{{posts.info.date.hint}}' }
          - {
              label: '{{posts.info.author.label}}',
              name: 'author',
              widget: 'relation',
              collection: 'authors',
              search_fields: ['title'],
              value_field: 'title',
              hint: '{{posts.info.author.hint}}',
            }
          - {
              label: '{{posts.info.excerpt.label}}',
              name: 'excerpt',
              widget: 'text',
              hint: '{{posts.info.excerpt.hint}}',
            }
      - { label: '{{posts.heroImage.label}}', name: 'image', widget: image, hint: '{{posts.heroImage.hint}}' }
      - { label: '{{posts.body.label}}', name: 'body', widget: 'markdown', hint: '{{posts.body.hint}}' }

  - name: 'categories'
    label: '{{categories.plural}}'
    label_singular: '{{categories.singular}}'
    folder: 'content/categories'
    create: true
    fields:
      - { label: '{{categories.title.label}}', name: 'title', widget: 'string', hint: '{{categories.title.hint}}' }
      - label: '{{categories.seo.label}}'
        name: 'seo'
        widget: 'object'
        summary: '{{fields.title}}'
        fields:
          - {
              label: '{{categories.seo.title.label}}',
              name: 'title',
              widget: 'string',
              hint: '{{categories.seo.title.hint}}',
            }
          - {
              label: '{{categories.seo.slug.label}}',
              name: 'slug',
              widget: 'string',
              hint: '{{categories.seo.slug.hint}}',
            }
          - {
              label: '{{categories.seo.description.label}}',
              name: 'description',
              widget: 'text',
              pattern: ['^.{140,160}$', '{{categories.seo.description.error}}'],
              hint: '{{categories.seo.description.hint}}',
            }
          - {
              label: '{{categories.seo.heading.label}}',
              name: 'heading',
              widget: 'string',
              hint: '{{categories.seo.heading.hint}}',
            }
      - { label: '{{categories.body.label}}', name: 'body', widget: 'markdown', hint: '{{categories.body.hint}}' }

  - name: 'authors'
    label: '{{authors.plural}}'
    label_singular: '{{authors.singular}}'
    folder: 'content/authors'
    create: true
    media_folder: ../photos
    public_folder: /
    fields:
      - { label: '{{authors.title.label}}', name: 'title', widget: 'string', hint: '{{authors.title.hint}}' }
      - { label: '{{authors.photo.label}}', name: 'photo', widget: 'image', hint: '{{authors.photo.hint}}' }
      - {
          label: '{{authors.email.label}}',
          name: 'email',
          widget: 'string',
          pattern: ['^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$', '{{authors.email.error}}'],
          hint: '{{authors.email.hint}}',
        }

  - name: 'pages'
    label: '{{pages.plural}}'
    label_singular: '{{pages.singular}}'
    folder: 'content/pages'
    create: true
    fields:
      - { label: '{{pages.title.label}}', name: 'title', widget: 'string', hint: '{{pages.title.hint}}' }
      - label: '{{pages.seo.label}}'
        name: 'seo'
        widget: 'object'
        summary: '{{fields.title}}'
        fields:
          - { label: '{{pages.seo.title.label}}', name: 'title', widget: 'string', hint: '{{pages.seo.title.hint}}' }
          - { label: '{{pages.seo.slug.label}}', name: 'slug', widget: 'string', hint: '{{pages.seo.slug.hint}}' }
          - {
              label: '{{pages.seo.description.label}}',
              name: 'description',
              widget: 'text',
              pattern: ['^.{140,160}$', '{{pages.seo.description.error}}'],
              hint: '{{pages.seo.description.hint}}',
            }
          - {
              label: '{{pages.seo.heading.label}}',
              name: 'heading',
              widget: 'string',
              hint: '{{pages.seo.heading.hint}}',
            }
      - { label: '{{pages.body.label}}', name: 'body', widget: 'markdown', hint: '{{pages.body.hint}}' }

  - name: 'settings'
    label: '{{settings.label}}'
    editor:
      preview: false
    files:
      - name: 'ui'
        label: '{{settings.ui.label}}'
        file: 'content/settings/ui.md'
        fields:
          - name: 'colors'
            label: '{{settings.ui.colors.label}}'
            widget: 'object'
            fields:
              - {
                  name: 'primary',
                  label: '{{settings.ui.colors.primary.label}}',
                  widget: 'color',
                  hint: '{{settings.ui.colors.primary.hint}}',
                }
              - {
                  name: 'secondary',
                  label: '{{settings.ui.colors.secondary.label}}',
                  widget: 'color',
                  hint: '{{settings.ui.colors.secondary.hint}}',
                }

      - name: 'homepage'
        label: '{{settings.home.label}}'
        file: 'content/settings/home-page.md'
        fields:
          - name: 'seo'
            label: '{{settings.home.seo.label}}'
            widget: 'object'
            summary: '{{fields.title}}'
            fields:
              - {
                  name: 'title',
                  label: '{{settings.home.seo.title.label}}',
                  widget: 'string',
                  hint: '{{settings.home.seo.title.hint}}',
                }
              - {
                  name: 'description',
                  label: '{{settings.home.seo.description.label}}',
                  widget: 'text',
                  pattern: ['^.{140,160}$', '{{settings.home.seo.description.error}}'],
                  hint: '{{settings.home.seo.description.hint}}',
                }
              - {
                  name: 'heading',
                  label: '{{settings.home.seo.heading.label}}',
                  widget: 'string',
                  hint: '{{settings.home.seo.heading.hint}}',
                }
          - {
              name: 'body',
              label: '{{settings.home.body.label}}',
              widget: 'markdown',
              hint: '{{settings.home.body.hint}}',
            }

      - name: 'navigation'
        label: '{{settings.navigation.label}}'
        file: 'content/settings/navigation.md'
        fields:
          - label: '{{settings.navigation.categories.label}}'
            name: 'categories'
            widget: 'list'
            hint: '{{settings.navigation.categories.hint}}'
            fields:
              - {
                  label: '{{settings.navigation.categories.category}}',
                  name: 'name',
                  widget: 'relation',
                  collection: 'categories',
                  search_fields: ['seo.title'],
                  value_field: 'seo.slug',
                  display_fields: ['seo.title'],
                }
          - label: '{{settings.navigation.pages.label}}'
            name: 'pages'
            widget: 'list'
            hint: '{{settings.navigation.pages.hint}}'
            fields:
              - {
                  label: '{{settings.navigation.pages.page}}',
                  name: 'name',
                  widget: 'relation',
                  collection: 'pages',
                  search_fields: ['seo.title'],
                  value_field: 'seo.slug',
                  display_fields: ['seo.title'],
                }

      - name: 'logo'
        label: '{{settings.logo.label}}'
        file: 'content/settings/logo.md'
        fields:
          - {
              label: '{{settings.logo.multicolor.label}}',
              name: 'multicolor',
              widget: 'code',
              hint: '{{settings.logo.multicolor.hint}}',
            }
          - {
              label: '{{settings.logo.onecolor.label}}',
              name: 'onecolor',
              widget: 'code',
              hint: '{{settings.logo.onecolor.hint}}',
            }

      - name: 'socialmedia'
        label: '{{settings.socialMedia.label}}'
        file: 'content/settings/social-media.md'
        fields:
          - label: '{{settings.socialMedia.links.label}}'
            name: 'links'
            widget: 'list'
            summary: '{{fields.name}} - {{fields.url}}'
            hint: '{{settings.socialMedia.links.hint}}'
            fields:
              - {
                  label: '{{settings.socialMedia.links.name.label}}',
                  name: 'name',
                  widget: 'select',
                  options:
                    [
                      'Behance',
                      'Discrod',
                      'Dribble',
                      'Facebook',
                      'GitHub',
                      'GitLab',
                      'Google',
                      'Instagram',
                      'LinkedIn',
                      'Medium',
                      'Pinterest',
                      'Pocket',
                      'RSS',
                      'Snapchat',
                      'StackOverflow',
                      'Telegram',
                      'TikTok',
                      'Twitter',
                      'YouTube',
                      'Yelp',
                    ],
                  hint: '{{settings.socialMedia.links.name.hint}}',
                }
              - {
                  label: '{{settings.socialMedia.links.url.label}}',
                  name: 'url',
                  widget: 'string',
                  pattern: ['^https?:\/\/.+', '{{settings.socialMedia.links.url.error}}'],
                  hint: '{{settings.socialMedia.links.url.hint}}',
                }

      - name: 'footer'
        label: '{{settings.footer.label}}'
        file: 'content/settings/footer.md'
        fields:
          - label: '{{settings.footer.pages.label}}'
            name: 'pages'
            widget: 'list'
            hint: '{{settings.footer.pages.hint}}'
            fields:
              - {
                  label: '{{settings.footer.pages.page}}',
                  name: 'page',
                  widget: 'relation',
                  collection: 'pages',
                  search_fields: ['seo.title'],
                  value_field: 'seo.slug',
                  display_fields: ['seo.title'],
                }
